In [1]:
import numpy as np

In [9]:
arr_int=np.random.randint(1,100,20)
print(arr_int)
arr_2d=arr_int.reshape(5,4)
print(arr_2d)

[75 31 45 16 41 75 60 22 76 86 30 55 83 81 50 63 35 41 11 94]
[[75 31 45 16]
 [41 75 60 22]
 [76 86 30 55]
 [83 81 50 63]
 [35 41 11 94]]


In [10]:
print(arr_2d[1:4])

[[41 75 60 22]
 [76 86 30 55]
 [83 81 50 63]]


In [11]:
print(arr_2d[3:])

[[83 81 50 63]
 [35 41 11 94]]


In [12]:
arr_2d_copy=arr_2d.copy()
print(arr_2d_copy)
arr_2d[3:]=99
print(arr_2d)

[[75 31 45 16]
 [41 75 60 22]
 [76 86 30 55]
 [83 81 50 63]
 [35 41 11 94]]
[[75 31 45 16]
 [41 75 60 22]
 [76 86 30 55]
 [99 99 99 99]
 [99 99 99 99]]


In [16]:
#Accessing the index:
print(arr_2d[1,2])

60


In [17]:
arr_2d[1,2]=100
print(arr_2d)

[[ 75  31  45  16]
 [ 41  75 100  22]
 [ 76  86  30  55]
 [ 99  99  99  99]
 [ 99  99  99  99]]


In [20]:
#Slicing with combination of rows and columns
print("Slicing with combination of rows & columns")
print(arr_2d[:2,1:])

Slicing with combination of rows & columns
[[ 31  45  16]
 [ 75 100  22]]


In [21]:
print(arr_2d[2:4,2:4])

[[30 55]
 [99 99]]


In [23]:
#Boolen condition in the numpy arrays:
print(arr_2d[arr_2d>80])

[100  86  99  99  99  99  99  99  99  99]


In [28]:
r=arr_2d[arr_2d>90]
print(r.reshape(3,3))

[[100  99  99]
 [ 99  99  99]
 [ 99  99  99]]


In [ ]:
# 9= 3x3 
# 12= 4x3 , 3x4 , 6x2

In [ ]:
# Array Arithmetics:
print("Arrays Arithmetics")
arr=np.arange(1,11)
print(arr)
arr1=np.arange(21,31)
print(arr1)

arrays arithmetics
[ 1  2  3  4  5  6  7  8  9 10]
[21 22 23 24 25 26 27 28 29 30]


In [ ]:
arr2 = arr1 + arr 
print("Add two arrays", arr2)
arr2 = arr1 - arr 
print("Subtract two arrays", arr2)
arr3 = arr1 * arr
print("Mutiplication of two arrays", arr3)

Add two array [22 24 26 28 30 32 34 36 38 40]
Subtract two array [20 20 20 20 20 20 20 20 20 20]
Mutiplication of two arrays [ 21  44  69  96 125 156 189 224 261 300]


In [38]:
# Addition, Subtraction, Multiplication, Division, √SquareRoot, and Square of two arrays generated above.
arr_square = arr * arr
print("Sqaure of Numpy Arr:", arr_square)

Sqaure of Numpy Arr: [  1   4   9  16  25  36  49  64  81 100]


In [45]:
print("√SquareRoot of Numpy Arr:", np.round(np.sqrt(arr), 2))

√SquareRoot of Numpy Arr: [1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.   3.16]


In [48]:
# ndenumerate
for idx, values in np.ndenumerate(arr):
    if values==5:
        print(f' Index of {values} is {idx}')

 Index of 5 is (4,)


In [36]:
for i in range(arr.size):
    if arr[i]==9:
        print(f'Index of {arr[i] is [i]}')

Index of False


In [1]:
import numpy as np

In [ ]:
#check there exist zero?
x=np.array([1,2,3])
print("Original Array",x)
print("Test if none of the elements of the array is zero")
print(np.all(x)) 

Original Array [1 2 3]
Test if none of the elements of the array is zero
True


In [12]:
#Test wheather any of the elements of given arrays is non-zero.
s=np.array([0,0,0,0])
print("Original Array:",s)
print("Test wheather any of elements of given array is non-zero")
print(np.any(s))

Original Array: [0 0 0 0]
Test wheather any of elements of given array is non-zero
False


In [13]:
#Infinite number:
x=np.array([1,0,np.inf,0])
print("Original Array:",x)
print("Test wheather any of element of given array is infinte")
print(np.isinf(x))

Original Array: [ 1.  0. inf  0.]
Test wheather any of element of given array is infinte
[False False  True False]


In [14]:
#nan= not a number 
x=np.array([1,0,np.nan,0])
print("Original Array:",x)
print("Test wheather any of element of given array is nan")
print(np.isnan(x))

Original Array: [ 1.  0. nan  0.]
Test wheather any of element of given array is nan
[False False  True False]


In [16]:
#complex and real + imaginary part:
x=np.array([1+2j,1+0j,4.5,3,2,2j])
print("Original Array:",x)
print("Test wheather any of element of given array is complex number")
print(np.iscomplex(x))

Original Array: [1. +2.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Test wheather any of element of given array is complex number
[ True False False False False  True]
